[package]
name = "harvest"
version = "0.1.0"
authors = ["Frank Groeneveld <frank@frankgroeneveld.nl>"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
serde = "1.0.99"
serde_json = "1.0.40"
chrono = "0.4.9"

[dependencies.gtk]
version = "0.7.0"
features = ["v3_22"]

[dependencies.gdk]
version = "0.11.0"
features = ["v3_22"]

[dependencies.gio]
version = "0.7.0"
features = ["v2_44"]